# Large font

# Width and height of one character, less padding.
[char]
w = 12
h = 16

# Padding between characters (both on screen and in font bitmap).
[pad]
w = 1
h = 1

[width_overrides]
# Punctuation
"(" = 8
")" = 8
"'" = 4
"\"" = 8
":" = 2
";" = 3
"<" = 9
"=" = 8
">" = 9
"I" = 2
"i" = 2
"l" = 6
"v" = 10
"z" = 11
# 'o' derived lowercase letters
"a" = 10
"b" = 10
"c" = 10
"d" = 10
"o" = 10
